### PR TITLE
add index by id

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
This adds the ability to index into `DashApp`, `Components` and collections of `Components` by id. Like
```julia
using Dash
myapp.app["my-id"]
```

This is mainly useful for testing purposes and a convenience feature.

### CODE REVIEW

**Comment by etpinard** [comment]
Hi @BeastyBlacksmith - nice to see someone making a feature PR to Dash.jl !

Does the python version of dash expose something similar from its public API or its [testing](https://github.com/plotly/dash/tree/dev/dash/testing) API?

If so, I think we could safely merge your PR.

If not, I (not a Plotly employee, I'm just a Dash.jl user with write rights to this repo) wouldn't be comfortable making the Dash.jl API diverge from the python version of dash.

**Comment by BeastyBlacksmith** [comment]
> It's a little funny to me that what you have here is `app[id]` though, would it make sense to change to `app.layout[id]`?

They work both

**Comment by BeastyBlacksmith** [comment]
bump.
> They work both

Should I add a test for this?

**Comment by etpinard** [comment]
Hi @BeastyBlacksmith, if you were to remove the `Base.getindex(app::Dash.DashApp, id::AbstractString)` method while keeping functionally for `app.layout[id]`, I could merge this PR and include it into Dash.jl v1.3.0 that I'd like to release at some point this week.

**Comment by BeastyBlacksmith** [comment]
I don't think it does any harm, but I removed it.

**Comment by etpinard** [comment]
Thanks for the PR @BeastyBlacksmith - merging !

**Pull request merged**
