### PR TITLE
Remove deprecated `Dash*` deps

### PR DESCRIPTION
**Pull request by etpinard**
which are now bundled in `Dash.jl` as of v1.0.

----

Discovered when running a [PackageCompiler.jl](https://julialang.github.io/PackageCompiler.jl/stable/index.html) compiled Dash.jl app where we currently get:

image

### CODE REVIEW

**Comment by waralex** [comment]
Hi!
These dependencies were added for a reason. If you remove it, then users, when migrating from an old version of Dash and having old versions of the components installed, will receive a name conflict at `using Dash, DashCoreComponents` without an explanation of why this happens.

As an option, I can update these component packages and not throw out the warnings with a certain environment variable set, if that helps you

P.S. Apparently I need to figure out how PackageCompiler works and include Dash testing with it in the release cycle :)

**Comment by etpinard** [comment]
> f you remove it, then users, when migrating from an old version of Dash and having old versions of the components installed, will receive a name conflict at `using Dash, DashCoreComponents` without an explanation of why this happens.

Great. Thanks for the explanation! 

I haven't been able to reproduce the name conflict you're mentioning though. Starting from

```jl
# main.jl
using Dash, DashHtmlComponents

app = dash()

app.layout = html_div() do
    html_button("CLICK", id = "btn"),
    html_div(id = "out")
end

callback!(app, Output("out", "children"),
               Input("btn", "n_clicks")) do n_clicks
    return "click #$(n_clicks)"
end

run_server(app, "0.0.0.0", 8050)
```

and

```jl
(try-Dash.jl-deprecated-deps) pkg> st
      Status `~/Documents/_/try-Dash.jl-deprecated-deps/Project.toml`
  [1b08a953] Dash v0.1.6
  [1b08a953] DashHtmlComponents v1.1.4
```

then 

```jl
julia> import Pkg; Pkg.add(url="https://github.com/etpinard/Dash.jl/", rev="dc6d150005faabb283ad921a92cdfeb0b0c77515")
   Resolving package versions...
    Updating `~/Documents/_/try-Dash.jl-deprecated-deps/Project.toml`
  [1b08a953] ~ Dash v0.1.6 ⇒ v1.1.1 `https://github.com/etpinard/Dash.jl/#dc6d150`
    Updating `~/Documents/_/try-Dash.jl-deprecated-deps/Manifest.toml`
  [1b08a953] ~ Dash v0.1.6 ⇒ v1.1.1 `https://github.com/etpinard/Dash.jl/#dc6d150`
  [1b08a953] - DashCoreComponents v1.17.1
  [1b08a953] - DashTable v4.12.0
  [692b3bcd] + JLLWrappers v1.3.0
  [0f8b85d8] + JSON3 v1.9.2
  [21216c6a] + Preferences v1.2.2
  [69024149] + StringEncodings v0.3.5
  [856f2bd8] + StructTypes v1.8.1
  [ddb6d928] + YAML v0.4.7
  [94ce4f54] + Libiconv_jll v1.16.1+1

(try-Dash.jl-deprecated-deps) pkg> st
      Status `~/Documents/_/try-Dash.jl-deprecated-deps/Project.toml`
  [1b08a953] Dash v1.1.1 `https://github.com/etpinard/Dash.jl/#dc6d150`
  [1b08a953] DashHtmlComponents v1.1.4

julia> include("main.jl")
[ Info: Listening on: 0.0.0.0:8050
```

appears to run without any issues.

----


> P.S. Apparently I need to figure out how PackageCompiler works and include Dash testing with it in the release cycle :)

Yep, looks like PackageCompiler uses the to-be-compiled app's Manifest.toml as the list of all dependencies to bundle which leads to these warnings even if `DashHtmlComponents`, `DashCoreComponents` and `DashTable` aren't used in one's app.

**Comment by etpinard** [comment]
> I haven't been able to reproduce the name conflict you're mentioning though

Oh nevermind, after restarting a julia session, we get:

```jl
(try-Dash.jl-deprecated-deps) pkg> st
      Status `~/Documents/_/try-Dash.jl-deprecated-deps/Project.toml`
  [1b08a953] Dash v1.1.1 `https://github.com/etpinard/Dash.jl/#dc6d150`
  [1b08a953] DashHtmlComponents v1.1.4

julia> include("main.jl")
WARNING: both DashHtmlComponents and Dash export "html_div"; uses of it in module Main must be qualified
ERROR: LoadError: UndefVarError: html_div not defined
Stacktrace:
 [1] top-level scope
   @ ~/Documents/_/try-Dash.jl-deprecated-deps/main.jl:5
 [2] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [3] top-level scope
   @ REPL[2]:1
in expression starting at /home/etienne/Documents/_/try-Dash.jl-deprecated-deps/main.jl:5
```

**Comment by etpinard** [comment]
@waralex would you like me to close this PR and open a new issue about the warnings displayed when running PackageCompiler complied apps?

**Comment by waralex** [comment]
@etpinard 
>would you like me to close this PR and open a new issue about the warnings displayed when running PackageCompiler complied apps?

Yep. I think this is the most correct  and convenient way

**Pull request closed without merging**
