### PR TITLE
handle empty children for index by id

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
unfortunately I missed this case in #203

### CODE REVIEW

**Comment by etpinard** [comment]
Great. 

Look like you added your commit on an outdated base branch.

Would you mind rebasing your branch off the latest `dev` and submitting a new PR? Thanks!

**Comment by BeastyBlacksmith** [comment]
done

**Comment by etpinard** [comment]
Come to think of it. The `Base.getindex(component::DashBase.Component, id::AbstractString)` definition is type-piracy

Would you mind moving it (along with its tests) to DashBase.jl ?

**Comment by BeastyBlacksmith** [comment]
I moved that, tests will fail until https://github.com/plotly/DashBase.jl/pull/5 is merged and released

**Comment by etpinard** [comment]
Essentially done in https://github.com/plotly/Dash.jl/pull/223

**Pull request closed without merging**
