### PR TITLE
Attempt at bringing `gen_resources` back to life

### PR DESCRIPTION
**Pull request by etpinard**
My attempt at updating the 18+ months old https://github.com/plotly/DashCoreResources tarball.

----

I do not have push rights to https://github.com/plotly/DashCoreResources, so I pushed to my fork https://github.com/etpinard/DashCoreResources, see [diff](https://github.com/plotly/DashCoreResources/compare/master...etpinard:DashCoreResources:master).

I needed to tweak the `Sources.toml` in https://github.com/plotly/Dash.jl/commit/a8f15a2ba597c4a33e34c1dbce391599ce8b67df as the dash renderer is no long a separate python package.

This isn't quite sufficient though. Using the new artifacts, I get

image

Any help here would be much appreciated!

### CODE REVIEW

**Comment by etpinard** [comment]
In the generated `DashCoreResources/resources/dash_renderer.yaml` diff, these lines

image

could be telling us something :thinking:

**Comment by alexcjohnson** [comment]
hmm something to do with the refactoring we did with Python Dash 2.0? I didn't think that moved the renderer but maybe it had some side-effect. Anyway I gave you write access to https://github.com/plotly/DashCoreResources, if that's still useful.

**Comment by etpinard** [comment]
I got the resources to load properly with https://github.com/plotly/Dash.jl/pull/208/commits/56a0ae2e49ff6daf521ff4652210227e2fb58141, there might a better way to do this. 

Briefly, we need to account for the differences between the [old](https://github.com/plotly/DashCoreResources/tree/694d3180f9fad530ada96c2de5e4141d58a7ca74/resources/dash_renderer_deps)  `dash_renderer_deps` file tree and the [new](https://github.com/etpinard/DashCoreResources/tree/6b5e00e34db5f22bce2c3ba7ffb49aa231528780/resources/dash_renderer_deps) one. The generated `dash_renderer.yaml` diff (see https://github.com/plotly/Dash.jl/pull/208#issuecomment-1590054538) get us close, but not quite to the finish line.

This results in two failing integration tests

image

to be continued ....

**Comment by etpinard** [comment]
### Update

I got the integration tests to pass again :tada: 

- commit https://github.com/plotly/Dash.jl/pull/208/commits/6eb9c061eabe7ae7045931f18ffce3d80f2d05b7 adapts the Promise in clientside callback test as now JS Promises do work inside clientside callbacks thanks to [dash#2009](https://github.com/plotly/dash/pull/2009), released in dash [`v2.4.0`](https://github.com/plotly/dash/blob/dev/CHANGELOG.md#240---2022-05-11)
   + It might be nice to adapt and include the other integration tests added in [dash#2009](https://github.com/plotly/dash/pull/2009) in Dash.jl while at it
- commit https://github.com/plotly/Dash.jl/pull/208/commits/95d05619387a80c6fdcfb19ae881cd2c8804176f adapts the devtools prop check test suite (essential what this [piece of a very large patch](https://github.com/plotly/dash/commit/c70ad1ec5f3cee5c614e30b835ce37fc93ae0237#diff-52c95a704467cd31db51bbb3698cf6e1915c1c074446f4ceb70471326edc5684) did in python) now that nested props are valid since [dash#1763](https://github.com/plotly/dash/pull/1763), released in dash [`v2.1.0`](https://github.com/plotly/dash/blob/dev/CHANGELOG.md#210---2022-01-22)

Now, the percy snapshots did generate two diffs:

image

image

which I'm not 100% sure were expected.

---


If any Dash.jl user is reading this, it would be nice to have some of you try out this branch in your dev environment

```
julia> import Pkg
julia> Pkg.add(url="https://github.com/plotly/Dash.jl", rev="bring-gen_resources-back-to-life")
```

thank you !!

**Comment by etpinard** [comment]
Now in https://github.com/plotly/Dash.jl/pull/212 - closing.

**Pull request closed without merging**
