### PR TITLE
Fixed examples

### PR DESCRIPTION
**Pull request by PallHaraldsson**
I tested first one, I guess all work now.

Maybe more punctuation, I left out periods intentionally at the end of some sentences.

jldoctest -> julia? I guess both work, not sure if either is older/outdated.

I know what you mean by callid"" but at first I thought last one of first triple quote missing. Possibly callid"<something>" (also callid""" ... """ possible, maybe not oo desirable here).

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
"failing check" should be a false alarm (first commit didn't even touch source code). Probably why I can't add the branch to my fork (or just I don't know how).

**Comment by PallHaraldsson** [comment]
You have "in Dasboards" and "for Dasboards module". There are typos, and I'm not sure if these (and where without typos) should be renamed to just Dash. It seems like copy past from old project.

**Comment by waralex** [comment]
@PallHaraldsson 
>You have "in Dasboards" and "for Dasboards module". There are typos, and I'm not sure if these (and where without typos) should be renamed to just Dash. It seems like copy past from old project.

Dashboards is my personal project that served as the basis for Dash. So the entire Dash is initially a copy paste of Dashboards :)

Thank you very much for your work. I haven't paid much attention to the documentation yet (since the interface is still subject to a lot of changes) and apparently this is my mistake. Plus I don't know English very well. I think I will take your changes as a basis and include them in the nearest PR with functionality https://github.com/plotly/Dash.jl/pull/39

P.S. I have a lot of work on my main job right now, and I plan to return to active Dash development in a couple of days

**Comment by PallHaraldsson** [comment]
I would be good to merge, to signal to users, the code is working.

It seems your English is fine.

As I said, typos, and copy-pasting. I left out changing anything I wasn't sure about. So I think it should be fine to merge right away. I told people at work I was using Dash, and one of them was also trying out and ran into the same two missing `using` statements I did.

**Pull request merged**
