### PR TITLE
Fix CircleCI

### PR DESCRIPTION
**Pull request by etpinard**

### CODE REVIEW

**Comment by etpinard** [comment]
https://github.com/plotly/Dash.jl/pull/239/commits/eb02e2accca16f4cf67b7f9ce28dc606e8d4054b makes the `build` workflow pass again.

Getting Percy back to :green_circle: will require more attention.

**Comment by etpinard** [comment]
The percy problems might be related to: https://github.com/plotly/dash/pull/2747

**Comment by etpinard** [comment]
Confirmed.

We pull in the latest `dev` dash.py changes on CircleCI here:

https://github.com/plotly/Dash.jl/blob/4d93ee8654a965eb188a7e90fad2f5f4c261c751/.circleci/config.yml#L42

meaning the changes in `dash.testing` from https://github.com/plotly/dash/pull/2747 we're pulled in.

Inspecting the changes in https://percy.io/plotly/dash.jl/builds/35406873 we see that only the filenames changed. The baselines are identical otherwise.

Unfortunately, looks like I am no longer able to approve changes up on Percy:


https://github.com/user-attachments/assets/0f7137fd-3c27-40ed-a3ce-54e97a87b78d

(the _Approve build_ button is disabled)

Can someone at Plotly (cc'ing https://github.com/gvwilson) approve these changes? Thank you!

**Comment by etpinard** [comment]
ping @gvwilson

**Review by gvwilson — APPROVED** [review]

**Pull request merged**
